add alpha tag to website
PollerAI/PollerAI.github.io pull request #2
Opened 2017-06-26 16:00 UTC by tw0517tw

2017-06-26 16:04 UTC, kpman commented
Could you add some screenshot about mobile and desktop version? @tw0517tw

2017-06-26 16:27 UTC, kpman requested changes

2017-06-26 16:27 UTC, kpman commented on css/custom.css
> +  .tag_alpha {
No underscore for class naming, use hyphen(-).
ex: `.tag-alpha`

2017-06-27 00:38 UTC, tw0517tw commented
![default](https://user-images.githubusercontent.com/1003146/27565921-fb57311a-5b13-11e7-9fb6-ec2f937afb82.png)
![default](https://user-images.githubusercontent.com/1003146/27565937-09d1dd30-5b14-11e7-8659-0189843a40e3.png)

2017-06-27 01:08 UTC, kpman approved these changes

2017-06-27 01:08 UTC, merged